# Subset of strings from defined sets
name: "licenseStatus"
description: "Status of the driver's license."
type: subset
min_amount: 1
max_amount: 2
separator: ";"
constrains:
  allowed_values: [valid, banned, suspended, none]
  unique: True
