name: "substanceUsed"
description: "Substance measured in drivers blood or breath."
type: subset
min_amount: 1
max_amount: 10
constraints:
  unique: true
  allowed_values:
    - "Acetorfín"
    - "Acetylfentanyl"
    - "Akrylfentanyl"
    - "Benzylón"
    - "BMDP"
    - "Brorfín"
    - "Butonitazén"
    - "Butyrfentanyl"
    - "Crotonylfentanyl"
    - "Cyklopropylfentanyl"
    - "Dezomorfín"
    - "Etazén"
    - "Etonitazepyn"
    - "Furanylfentanyl"
    - "Heroín"
    - "Izotonitazén"
    - "Ketobemidón"
    - "Metonitazén"
    - "Metoxyacetylfentanyl"
    - "MPPP"
    - "Ocfentanyl"
    - "PEPAP"
    - "THF-F"
    - "Tetrahydrofuranylfentanyl"
    - "Tiofentanyl"
    - "BZP"
    - "Brolamfetamín"
    - "DOB"
    - "Bromazolam"
    - "chlóredron"
    - "klefedron"
    - "kanabicyklohexanol"
    - "levonantradol"
    - "DET"
    - "Difenidín"
    - "Diklazepam"
    - "Dimetoxyamfetamín"
    - "DMA"
    - "Dipentylón"
    - "DMHP"
    - "DMT"
    - "DOET"
    - "DOI"
    - "Efenidín"
    - "EPE"
    - "NEDPA"
    - "Eticyklidín"
    - "PCE"
    - "Etryptamín"
    - "MDEC"
    - "Eutylon"
    - "Flubromazolam"
    - "FUB-AMB"
    - "MMB-FUBINACA"
    - "AMB-FUBINACA"
    - "tetrahydrokanabidiol"
    - "HHC"
    - "hexahydrokanabinol"
    - "hexahydrokanabihexol"
    - "HHC-O"
    - "hexahydrokanabinol acetát"
    - "HHC-P"
    - "hexahydrokanabiforol"
    - "HHCP acetát"
    - "hexahydrokanabiforol acetát"
    - "kanbizol"
    - "IPPH"
    - "IPH"
    - "IPD"
    - "IPPD"
    - "pyrán"
    - "Klonazolam"
    - "LSD"
    - "MDPEP"
    - "MDPHP"
    - "Mefedrón"
    - "mCPP"
    - "Metiopropamín"
    - "MPA"
    - "Mezkalín"
    - "Metkatinón"
    - "Metoxetamín (MXE)"
    - "MDA"
    - "sass"
    - "MMDA"
    - "Metylbenzodioxolylbutánamín"
    - "MBDB"
    - "MDMA"
    - "Metyléndioxypyrovalerón"
    - "MDPV"
    - "Metylón"
    - "MXPr"
    - "metoxpropamín"
    - "efylón"
    - "NEP"
    - "Parahexyl"
    - "PMA"
    - "PMMA"
    - "Pentedrón"
    - "Psilocybín"
    - "Psilocín"
    - "Rolicyklidín"
    - "PHP"
    - "PCPY"
    - "Tenamfetamín"
    - "Tenocyklidín"
    - "TCP"
    - "THC"
    - "tetrahydrokanabinol"
    - "THCB"
    - "tetrahydrokanabutol"
    - "THCH"
    - "tetrahydrokanabihexol"
    - "THCP"
    - "tetrahydrokanabiforol"
    - "Trimetoxyamfetamín"
    - "TMA"
    - "Acetylmetadol"
    - "Alfacetylmetadol"
    - "Alfameprodín"
    - "Alfametadol"
    - "Alfaprodín"
    - "Alfentanil"
    - "Alylprodín"
    - "Anileridín"
    - "Benzetidín"
    - "Benzylmorfín"
    - "Betacetylmetadol"
    - "Betameprodín"
    - "Betametadol"
    - "Betaprodín"
    - "Bezitramid"
    - "Buprenorfín"
    - "Carfentanyl"
    - "Dextromoramid"
    - "Dietyltiambutén"
    - "Difenoxylát"
    - "Dihydroetorfín"
    - "Dihydromorfín"
    - "Dimefeptanol"
    - "Dimenoxadol"
    - "Dimetyltiambutén"
    - "Dioxafetylbutyrát"
    - "Dipipanón"
    - "Drotebanol"
    - "Ekgonín a jeho deriváty a estery"
    - "Etonitazén"
    - "Etorfín"
    - "Etoxeridín"
    - "Etylmetyltiambutén"
    - "Fenadoxón"
    - "Fenampromid"
    - "Fenazocín"
    - "Fenibut"
    - "Fenomorfán"
    - "N-fenetylmorfinán-3-ol"
    - "Fenoperidín"
    - "Fentanyl"
    - "Furetidín"
    - "Hydrokodón"
    - "Hydromorfinol"
    - "Hydromorfón"
    - "Hydroxypetidín"
    - "Izometadón"
    - "Ketamín"
    - "Klonitazén"
    - "Kodoxím"
    - "Kokaín"
    - "metylester benzoylekgonínu"
    - "Koncentrát makovej slamy"
    - "Levometorfán"
    - "Levofenacylmorfán"
    - "Levoramid"
    - "Levorfanol"
    - "Metadón"
    - "Metadónový medziprodukt"
    - "Metazocín"
    - "Metopón"
    - "Metyldezorfín"
    - "Metyldihydromorfín"
    - "Morferidín"
    - "Morfín"
    - "Morfínmetobromid"
    - "N-metylmorfíniumbromid"
    - "Myrofín"
    - "Nikomorfín"
    - "Nopipanón"
    - "Noracymetadol"
    - "Norlevorfanol"
    - "Normetadón"
    - "Normorfín"
    - "Ópium"
    - "Oripavín"
    - "Oxykodón"
    - "Oxymorfón"
    - "Petidín"
    - "Piminodín"
    - "Piritramid"
    - "Proheptazín"
    - "Properidín"
    - "Racemetorfán"
    - "Racemoramid"
    - "Racemorfán"
    - "Remifentanil"
    - "Sufentanil"
    - "Tapentadol"
    - "Tebaín"
    - "Tebakón"
    - "Tilidín"
    - "Trimepiridín"
    - "Xylazín"
    - "Amfetamín"
    - "Amineptin"
    - "Dexamfetamín"
    - "Dronabinol"
    - "Fencyklidín"
    - "Fenetylín"
    - "Fenmetrazín"
    - "GHB"
    - "kyselina 4-hydroxybutánová"
    - "Levamfetamín"
    - "Levometamfetamín"
    - "Meklokvalón"
    - "Metakvalón"
    - "Metamfetamín"
    - "Metamfetamín-racemát"
    - "Sekobarbital"
    - "Zipeprol"
    - "Acetyldihydrokodeín"
    - "Dextropropoxyfen"
    - "Dihydrokodeín"
    - "Etylmorfín"
    - "Folkodín"
    - "Kodeín"
    - "Nikodikodín"
    - "Nikokodín"
    - "Norkodeín"
    - "N-demetylkodeín"
    - "Propiram"
    - "Alobarbital"
    - "Alprazolam"
    - "Amfepramón"
    - "Aminorex"
    - "Amobarbital"
    - "Barbital"
    - "Bentazepam"
    - "Benzfetamín"
    - "Bromazepam"
    - "Brotizolam"
    - "Butalbital"
    - "Butobarbital"
    - "Cyklobarbital"
    - "Delorazepam"
    - "Diazepam"
    - "Estazolam"
    - "Etizolam"
    - "Etchlórvinol"
    - "Etinamát"
    - "Etylamfetamín"
    - "N-etyl-(1-fenylpropán-2-yl)amín"
    - "Etylloflazepát"
    - "Fenazepam"
    - "Fendimetrazín"
    - "Fenkamfamín"
    - "Fenobarbital"
    - "Fenproporex"
    - "Fentermín"
    - "Flualprazolam"
    - "Fludiazepam"
    - "Flunitrazepam"
    - "Flurazepam"
    - "GBL"
    - "dihydrofurán-2(3H)-ón"
    - "Glutetimid"
    - "Halazepam"
    - "Haloxazolam"
    - "Chlórdiazepoxid"
    - "Kamazepam"
    - "Katín"
    - "Ketazolam"
    - "Klobazam"
    - "Klonazepam"
    - "Klorazepat"
    - "Klotiazepam"
    - "Kloxazolam"
    - "Lefetamín"
    - "Loprazolam"
    - "Lorazepam"
    - "Lormetazepam"
    - "Mazindol"
    - "Medazepam"
    - "Mefenorex"
    - "Meprobamát"
    - "Mezokarb"
    - "Metylfenobarbital"
    - "Metyprylón"
    - "Midazolam"
    - "Nimetazepam"
    - "Nitrazepam"
    - "Nordazepam"
    - "Oxazepam"
    - "Oxazolam"
    - "Pemolín"
    - "Pentazocín"
    - "Pentobarbital"
    - "Pinazepam"
    - "Pipradol"
    - "Prazepam"
    - "Pyrovalerón"
    - "Sekbutabarbital"
    - "Temazepam"
    - "Tetrazepam"
    - "Triazolam"
    - "Vinylbital"
    - "Zolpidem"
    - "alkohol"
    - "ethanol"
    - "ethanol"
    - "cannabis"
    - "kannabis"
    - "konopie"
    - "konopy"
    - "alcohol"
    - "cannabis"

